# Generated by Django 4.0.6 on 2022-07-24 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField(unique=True)),
                ('eventName', models.CharField(max_length=20)),
                ('eventLocation', models.CharField(max_length=20)),
                ('eventRoom', models.CharField(max_length=15)),
                ('eventDate', models.DateTimeField()),
                ('eventSpeaker', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('conferenceName', models.CharField(max_length=60)),
                ('conferenceOrganizer', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('dateRange', models.DurationField(blank=True, default=datetime.timedelta(days=1))),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventHandler.event')),
            ],
        ),
    ]
