# Generated by Django 4.0.6 on 2022-07-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandler', '0002_alter_conference_conferencename_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
